name = "medium-blog"
main = "src/index.ts"
compatibility_date = "2024-03-01"


[build]
command = "npm run build"


# Format: prisma://<host>/?api_key=<jwt>
# JWT contains: header.payload.signature
[vars]
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjM4M2ZiNWQtMTRkYS00ZTNlLTk3ZDAtMTlmMmI5Y2NhM2RhIiwidGVuYW50X2lkIjoiYjU4MTI1ZTZjMGQxOWM4Y2NmMWU1ODhjM2MwMjdhYTNkMjdhN2EzZTBhNzg1ZGIxNGQzZjg0YjJhMjllNDE0ZSIsImludGVybmFsX3NlY3JldCI6IjNkMWIwZDg2LThhMzctNDdiOS04NjY1LTc3ODc0ZWIxY2Y2YSJ9._CwfgDq-ssSa5nXrgCarxZmeIo1mZ-8h-Tw6VLOGh9k"

JWT_SECRET = "your-secret-key-here"

[[routes]]
pattern = "https://backend.vatscode.workers.dev/*"
zone_id = "YOUR_ZONE_ID"